services:
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - 5673:5672
      - 15673:15672
    restart: always
  web:
    build: ./web
    environment:
      WAIT_HOSTS: mongodb:27017, rabbitmq:5672
      CONN_STR: mongodb://scholarlink:scholarlink@mongodb/mydb
    volumes:
      - ./web:/app
    ports:
      - 8080:8080
    restart: always
  recommender:
    build: ./recommender
    environment:
      WAIT_HOSTS: mongodb:27017, rabbitmq:5672
      CONN_STR: mongodb://scholarlink:scholarlink@mongodb/mydb
    env_file:
      - ./recommender/.env
    volumes:
      - ./recommender:/app
    restart: always
  mail:
    build: ./mail
    environment:
      WAIT_HOSTS: mongodb:27017, rabbitmq:5672
      CONN_STR: mongodb://scholarlink:scholarlink@mongodb/mydb
      CRON_SCHEDULE: "*/30 * * * * *"
    env_file:
      - ./mail/.env
    volumes:
      - ./mail:/app
    restart: always
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: mydb
    volumes:
      - data:/data/db
      - ./scripts:/docker-entrypoint-initdb.d
    restart: always
volumes:
  data: