services:
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - 5673:5672
      - 15673:15672
  web:
    build: ./server
    environment:
      WAIT_HOSTS: mongodb:27017, rabbitmq:5672
      CONN_STR: mongodb://admin:admin@mongodb
    volumes:
      - ./server:/app
    ports:
      - 8080:8080
  ml:
    build: ./ml
    environment:
      WAIT_HOSTS: mongodb:27017, rabbitmq:5672 
      CONN_STR: mongodb://admin:admin@mongodb
    env_file:
      - ./ml/.env
    volumes:
      - ./ml:/app
  mail:
    build: ./mail
    environment:
      WAIT_HOSTS: mongodb:27017, rabbitmq:5672
      CONN_STR: mongodb://admin:admin@mongodb
    env_file:
      - ./mail/.env
    volumes:
      - ./mail:/app
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - data:/data/db
volumes:
  data: