const allInterests = [
  "Behavioral Sciences",
  "Biomedicine",
  "Business and Management",
  "Chemistry",
  "Climate",
  "Computer Science",
  "Earth Sciences",
  "Economics",
  "Education",
  "Energy",
  "Engineering",
  "Environment",
  "Geography",
  "Psychology",
  "Political Science",
  "History",
  "Law",
  "Life Sciences",
  "Materials Science",
  "Mathematics",
  "Pharmacy",
  "Philosophy",
  "Physics",
  "Public Health",
  "Social Sciences",
  "Statistics",
  "Literature",
];

module.exports = allInterests;
